version: '3'

services:
    mysql:
        build: ./mysql/
        container_name: my_mysql
        restart: always
        env_file:
            - ./env_file
        volumes:
            - ./mysql/database:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            db_net:

    guacd:
        image: guacamole/guacd
        container_name: my_guacd
        restart: always
        networks:
            guac_net:

    guacamole:
        image: guacamole/guacamole
        container_name: my_guacamole
        restart: always
        env_file:
            - ./env_file        
        networks:
            db_net:
            guac_net:
            proxy_net:
        depends_on:
            - guacd
            - mysql

    nginx:
        image: nginx
        container_name: my_nginx
        restart: always
        networks:
            proxy_net:
        depends_on:
            - guacamole
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/certs:/etc/certs
        ports:
            - "80:80"
            - "443:443"

networks:
    db_net:
    guac_net:
    proxy_net:
