FROM guacamole/guacamole

COPY mysql-connector-java-5.1.46-bin.jar /opt/guacamole/mysql/

COPY mysql-connector-java-5.1.47.tar /opt/guacamole/mysql/

COPY mysql-connector-java-8.0.16.tar /opt/guacamole/mysql/

# Remove any old/unused connector files
#RUN rm /opt/guacamole/mysql/mysql-connector-java-5.1.35-bin.jar
