FROM guacamole/guacamole

# Remove any old/unused connector files
#RUN rm /opt/guacamole/mysql/mysql-connector-java-*

# Select the connector you wish to use and uncomment it.
#COPY mysql-connector-java-5.1.46-bin.jar /opt/guacamole/mysql/
#COPY mysql-connector-java-5.1.47.tar /opt/guacamole/mysql/
#COPY mysql-connector-java-8.0.16.tar /opt/guacamole/mysql/

